name: jupyter_dashboards_workshop
channels:
  - conda-forge
  - defaults
dependencies:
#  - python==3.4.1
#  - notebook
#  - jupyter_dashboards
#  - jupyter_dashboards_bundlers
#  - matplotlib
  - folium
#  - ipywidgets=7
#  - qgrid
#  - plotly
#  - beakerx
